#!/bin/sh

if [ -f devel.pid ]
then
    echo "Already running at PID `cat devel.pid`"
    exit 1
fi
CMD="$(nix-build --no-out-link --show-trace -E '
((import <nixpkgs> {})
 .callPackage ./src/nix/lib/clojure.nix {})
.callPackage ./project.nix {}
')/bin/dwn devel.socket"

$CMD &
CHILDPID=$!
echo "Running '$CMD' with PPID $$; CPID $CHILDPID"
echo "$CHILDPID" > devel.pid
cleanup () {
    rm devel.pid
    kill $CHILDPID
}
trap cleanup EXIT
wait $CHILDPID
exit $?
